// Code generated by protoc-gen-go.
// source: stormgo.proto
// DO NOT EDIT!

/*
Package gostorm is a generated protocol buffer package.

It is generated from these files:
	stormgo.proto

It has these top-level messages:
	Init
	Command
	SpoutEmit
	BoltEmit
	Pid
	ShellMsg
*/
package gostorm

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Init struct {
	PidDir           *string `protobuf:"bytes,1,req" json:"PidDir,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Init) Reset()         { *m = Init{} }
func (m *Init) String() string { return proto.CompactTextString(m) }
func (*Init) ProtoMessage()    {}

func (m *Init) GetPidDir() string {
	if m != nil && m.PidDir != nil {
		return *m.PidDir
	}
	return ""
}

type Command struct {
	Command          *string `protobuf:"bytes,1,req" json:"Command,omitempty"`
	Id               *string `protobuf:"bytes,2,opt" json:"Id,omitempty"`
	Msg              *string `protobuf:"bytes,3,opt" json:"Msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}

func (m *Command) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *Command) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Command) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type SpoutEmit struct {
	Command          *string  `protobuf:"bytes,1,opt" json:"Command,omitempty"`
	Id               *string  `protobuf:"bytes,2,opt" json:"Id,omitempty"`
	Comp             *string  `protobuf:"bytes,3,opt" json:"Comp,omitempty"`
	Stream           *string  `protobuf:"bytes,4,opt" json:"Stream,omitempty"`
	Task             *int64   `protobuf:"varint,5,opt" json:"Task,omitempty"`
	Tuple            []string `protobuf:"bytes,6,rep" json:"Tuple,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SpoutEmit) Reset()         { *m = SpoutEmit{} }
func (m *SpoutEmit) String() string { return proto.CompactTextString(m) }
func (*SpoutEmit) ProtoMessage()    {}

func (m *SpoutEmit) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *SpoutEmit) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *SpoutEmit) GetComp() string {
	if m != nil && m.Comp != nil {
		return *m.Comp
	}
	return ""
}

func (m *SpoutEmit) GetStream() string {
	if m != nil && m.Stream != nil {
		return *m.Stream
	}
	return ""
}

func (m *SpoutEmit) GetTask() int64 {
	if m != nil && m.Task != nil {
		return *m.Task
	}
	return 0
}

func (m *SpoutEmit) GetTuple() []string {
	if m != nil {
		return m.Tuple
	}
	return nil
}

type BoltEmit struct {
	Command          *string  `protobuf:"bytes,1,opt" json:"Command,omitempty"`
	Anchors          []string `protobuf:"bytes,2,rep" json:"Anchors,omitempty"`
	Stream           *string  `protobuf:"bytes,3,opt" json:"Stream,omitempty"`
	Task             *int64   `protobuf:"varint,4,opt" json:"Task,omitempty"`
	Tuple            []string `protobuf:"bytes,5,rep" json:"Tuple,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BoltEmit) Reset()         { *m = BoltEmit{} }
func (m *BoltEmit) String() string { return proto.CompactTextString(m) }
func (*BoltEmit) ProtoMessage()    {}

func (m *BoltEmit) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *BoltEmit) GetAnchors() []string {
	if m != nil {
		return m.Anchors
	}
	return nil
}

func (m *BoltEmit) GetStream() string {
	if m != nil && m.Stream != nil {
		return *m.Stream
	}
	return ""
}

func (m *BoltEmit) GetTask() int64 {
	if m != nil && m.Task != nil {
		return *m.Task
	}
	return 0
}

func (m *BoltEmit) GetTuple() []string {
	if m != nil {
		return m.Tuple
	}
	return nil
}

type Pid struct {
	Pid              *int64 `protobuf:"varint,1,req" json:"Pid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Pid) Reset()         { *m = Pid{} }
func (m *Pid) String() string { return proto.CompactTextString(m) }
func (*Pid) ProtoMessage()    {}

func (m *Pid) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

type ShellMsg struct {
	Command          *string  `protobuf:"bytes,1,opt" json:"Command,omitempty"`
	Id               *string  `protobuf:"bytes,2,opt" json:"Id,omitempty"`
	Anchors          []string `protobuf:"bytes,3,rep" json:"Anchors,omitempty"`
	Stream           *string  `protobuf:"bytes,4,opt" json:"Stream,omitempty"`
	Task             *int64   `protobuf:"varint,5,opt" json:"Task,omitempty"`
	NeedTaskIds      *bool    `protobuf:"varint,6,opt" json:"NeedTaskIds,omitempty"`
	Msg              *string  `protobuf:"bytes,7,opt" json:"Msg,omitempty"`
	Name             *string  `protobuf:"bytes,8,opt" json:"Name,omitempty"`
	Params           *string  `protobuf:"bytes,9,opt" json:"Params,omitempty"`
	Level            *int64   `protobuf:"varint,10,opt" json:"Level,omitempty"`
	Tuple            []string `protobuf:"bytes,11,rep" json:"Tuple,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ShellMsg) Reset()         { *m = ShellMsg{} }
func (m *ShellMsg) String() string { return proto.CompactTextString(m) }
func (*ShellMsg) ProtoMessage()    {}

func (m *ShellMsg) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *ShellMsg) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ShellMsg) GetAnchors() []string {
	if m != nil {
		return m.Anchors
	}
	return nil
}

func (m *ShellMsg) GetStream() string {
	if m != nil && m.Stream != nil {
		return *m.Stream
	}
	return ""
}

func (m *ShellMsg) GetTask() int64 {
	if m != nil && m.Task != nil {
		return *m.Task
	}
	return 0
}

func (m *ShellMsg) GetNeedTaskIds() bool {
	if m != nil && m.NeedTaskIds != nil {
		return *m.NeedTaskIds
	}
	return false
}

func (m *ShellMsg) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *ShellMsg) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ShellMsg) GetParams() string {
	if m != nil && m.Params != nil {
		return *m.Params
	}
	return ""
}

func (m *ShellMsg) GetLevel() int64 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *ShellMsg) GetTuple() []string {
	if m != nil {
		return m.Tuple
	}
	return nil
}
